# Use postgres/example user/password credentials
version: "3.9"

services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - db_data:/var/lib/posgresql_shotseek/data
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb

    environment:
      POSTGRES_DB: shotseek
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      ports: "5432:5432"

  # adminer:
  #   image: adminer
  #   restart: always

volumes:
  db_data:
    # driver: local
